apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
        io.kompose.service: web
    name: web
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: web
    strategy: {}
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert
                kompose.version: 1.21.0 (992df58d8)
            creationTimestamp: null
            labels:
                io.kompose.service: web
        spec:
            containers:
                - args:
                      - npm
                      - run
                      - dev
                  env:
                      - name: ADMIN_EMAIL
                        valueFrom:
                            configMapKeyRef:
                                key: ADMIN_EMAIL
                                name: env
                      - name: ADMIN_NAME
                        valueFrom:
                            configMapKeyRef:
                                key: ADMIN_NAME
                                name: env
                      - name: ADMIN_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                key: ADMIN_PASSWORD
                                name: env
                      - name: JWT_SECRET
                        valueFrom:
                            configMapKeyRef:
                                key: JWT_SECRET
                                name: env
                      - name: MONGO_DB
                        valueFrom:
                            configMapKeyRef:
                                key: MONGO_DB
                                name: env
                      - name: MONGO_HOST
                        valueFrom:
                            configMapKeyRef:
                                key: MONGO_HOST
                                name: env
                      - name: SMTP_HOST
                        valueFrom:
                            configMapKeyRef:
                                key: SMTP_HOST
                                name: env
                      - name: SMTP_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                key: SMTP_PASSWORD
                                name: env
                      - name: SMTP_PORT
                        valueFrom:
                            configMapKeyRef:
                                key: SMTP_PORT
                                name: env
                      - name: SMTP_SECURE
                        valueFrom:
                            configMapKeyRef:
                                key: SMTP_SECURE
                                name: env
                      - name: SMTP_USER
                        valueFrom:
                            configMapKeyRef:
                                key: SMTP_USER
                                name: env
                  image: web
                  imagePullPolicy: Never
                  name: web
                  ports:
                      - containerPort: 3000
                  resources: {}
            restartPolicy: Always
            serviceAccountName: ''
            volumes: null
status: {}
